# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = kdeconnectd
exec-once = sleep 2 && if omarchy-ac-present; then ~/.config/omarchy/custom-powerprofiles-set.sh ac; else ~/.config/omarchy/custom-powerprofiles-set.sh battery; fi
